In [7]:
from pathlib import Path
import numpy as np

In [3]:
summary_path = Path('./result/')

print(list(summary_path.glob('*')))

[PosixPath('result/cycle_resnet50_summary.txt'), PosixPath('result/cycle_t_summary.txt'), PosixPath('result/cycle_tiny_bert_summary.txt')]


In [4]:
def makeblock(argparse, n): 
    tmp = np.array(argparse[:-1],dtype=np.int64)
    tmp1 = np.array(np.array_split(tmp,n),dtype=object)
    ret = np.array([],dtype=np.int64)
    for i in tmp1:
        ret = np.append(ret,np.sum(i,dtype=np.int64))
    return ret

In [12]:
name=[]
block = []
graph = dict()
    
for file in summary_path.glob('*'):
    f= open(file,'r')
    data = f.readlines()
    count = 0
    for T in data:
        T = T.replace("\n", "")
        L = T.split(' ')
        if L[0] == 'Systolic':
            count+=1
        if L[0] == 'DNN':
            if L[-1][:-12] not in name:
                name.append(L[-1][:-12])
        if len(T.split(' ')) > 9:
            block.append(makeblock(T.split(' '), 6))

In [14]:
print(name)

['resnet50', 't', 'tiny_bert']


In [10]:
f= open('./summary.txt','r')
data = f.readlines()
count = 0
name=[]
block = []
for T in data:
    T = T.replace("\n", "")
    L = T.split(' ')
    if L[0] == 'Systolic':
        count+=1
    if L[0] == 'DNN':
        if L[-1][:-12] not in name:
            name.append(L[-1][:-12])
    if len(T.split(' ')) > 9:
        block.append(makeblock(T.split(' '), 6))

In [15]:
print(name)

['resnet50', 't', 'tiny_bert']


In [11]:
block

[array([2836257984,  337128624,   62015184,    9783144,    5470952,
           2530496]),
 array([17372928, 16633344, 16633344, 16633344, 16633344, 15904116]),
 array([4729480000, 1207817072,  256889360,   47359480,   40592584,
           9341904]),
 array([1418128992,  163534364,   15579060,    2483418,    1413430,
            673904]),
 array([4689984, 4498944, 4498944, 4498944, 4498944, 4313466]),
 array([2049838560,  302581468,   64598660,   12053118,   10342640,
           2538648]),
 array([709365552,  81867534,   7789530,    651957,    380875,    190112]),
 array([2832672, 2724864, 2724864, 2724864, 2724864, 2620221]),
 array([946695680, 102043774,  18898876,   3179223,   2732372,    739932])]